version: '3.7'
services:
  web:
    build: .
    container_name: marine_model_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A celery_worker worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
